spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloTreGatti
    username: root
    password: c620918fazuKl420
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
